task:
  script: autoreconf -i && ./configure --enable-warning-as-error && make all distcheck
  matrix:
    container:
      matrix:
        image: gcc:latest
        image: gcc:8
#     image: gcc:7
# osx_instance:
#   matrix:
#     image: mojave-xcode
#     image: mojave-xcode-10.3
# freebsd_instance:
#   matrix:
#     image_family: freebsd-13-0-snap
#     image_family: freebsd-12-1-snap

