# Works
#gcc_task:
#  prep_script: autoreconf -i
#  configure_script: ./configure --enable-warning-as-error
#  make_script: make all
## check_script: make distcheck
#  container:
#    matrix:
#      image: gcc:latest
##     image: gcc:8
##     image: gcc:7

# This fails due to: missing aclocal
osx_task:
  brew_script: brew install autoconf automake
  prep_script: autoreconf -i
# configure_script: ./configure --enable-warning-as-error
# make_script: make all
# check_script: make distcheck
  osx_instance:
    matrix:
      image: mojave-xcode
#     image: mojave-xcode-10.3

# This fails due to: missing autoreconf
#freebsd_task:
#  prep_script: autoreconf -i
## configure_script: ./configure --enable-warning-as-error
## make_script: make all
## check_script: make distcheck
#  freebsd_instance:
#    matrix:
#      image_family: freebsd-13-0-snap
##     image_family: freebsd-12-1-snap

