# Note: I do not know (yet) how to do Cirrus CI with clang

clang_task:
  prep_script: autoreconf -i
#  configure_script: ./configure --enable-warning-as-error	# fails with: -Werror=zero-length-bounds
  configure_script: ./configure
  make_script: make all
  check_script: '[ master != "$CIRRUS_BRANCH" ] && [ -z "$CIRRUS_PR" ] || make distcheck'
  container:
    image: clang:latest

